---
exclude: ^(marda_registry/data/)
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
          - id: check-symlinks
          - id: check-yaml
          - id: check-json
          - id: destroyed-symlinks
          - id: end-of-file-fixer
          - id: requirements-txt-fixer
            name: Fix requirements*.txt
            files: ^requirements.*\.txt$
          - id: trailing-whitespace

    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.3
      hooks:
          - id: yamlfmt
            args: [--width, '80']

    - repo: https://github.com/adrienverge/yamllint.git
      rev: v1.35.1 # or higher tag
      hooks:
          - id: yamllint
            args: [--format, parsable, --strict, -d, '{line-length: {max: 100}}']

    - repo: https://github.com/psf/black
      rev: 24.3.0
      hooks:
          - id: black
            name: Blacken

    - repo: https://github.com/pycqa/flake8
      rev: 7.0.0
      hooks:
          - id: flake8

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.9.0
      hooks:
          - id: mypy
            name: MyPy
            additional_dependencies: [types-all, pydantic~=1.10]

    - repo: https://github.com/PyCQA/isort
      rev: 5.13.2
      hooks:
          - id: isort
            name: isort
